# Generated by Django 6.0 on 2026-01-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_remove_sancaulong_giacodinh_datsan_lich_tap_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datsan",
            name="ngayKetThuc",
            field=models.DateField(
                blank=True, null=True, verbose_name="Ngày kết thúc đợt"
            ),
        ),
        migrations.AlterField(
            model_name="datsan",
            name="ngayBatDau",
            field=models.DateField(verbose_name="Ngày bắt đầu chơi"),
        ),
    ]
