# Generated by Django 6.0 on 2026-01-04 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_datsan_ngayketthuc_alter_datsan_ngaybatdau"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sancaulong",
            options={
                "ordering": ["tenSan"],
                "verbose_name": "Sân cầu lông",
                "verbose_name_plural": "Quản lý Sân",
            },
        ),
        migrations.CreateModel(
            name="BinhLuan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("noi_dung", models.TextField(verbose_name="Nội dung")),
                ("ngay_tao", models.DateTimeField(auto_now_add=True)),
                (
                    "bai_dang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="binh_luan_set",
                        to="members.baidang",
                    ),
                ),
                (
                    "nguoi_binh_luan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="members.binhluan",
                    ),
                ),
            ],
            options={
                "ordering": ["ngay_tao"],
            },
        ),
    ]
