# Generated by Django 6.0 on 2026-01-05 02:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0005_alter_binhluan_options_alter_binhluan_bai_dang_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="baidang",
            options={
                "verbose_name": "Bài viết diễn đàn",
                "verbose_name_plural": "Quản lý Diễn đàn",
            },
        ),
        migrations.AlterModelOptions(
            name="binhluan",
            options={
                "verbose_name": "Bình luận",
                "verbose_name_plural": "Bình luận bài viết",
            },
        ),
        migrations.AlterModelOptions(
            name="hoithoaikhachhang",
            options={},
        ),
        migrations.AlterModelOptions(
            name="hotro",
            options={},
        ),
        migrations.AlterModelOptions(
            name="sancaulong",
            options={
                "verbose_name": "Sân cầu lông",
                "verbose_name_plural": "Quản lý Sân",
            },
        ),
        migrations.AddField(
            model_name="baidang",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="datsan",
            name="da_checkin",
            field=models.BooleanField(default=False, verbose_name="Khách đã đến sân"),
        ),
        migrations.AddField(
            model_name="datsan",
            name="ly_do_huy",
            field=models.TextField(
                blank=True, null=True, verbose_name="Lý do hủy (nếu có)"
            ),
        ),
        migrations.AddField(
            model_name="datsan",
            name="phuong_thuc_thanh_toan",
            field=models.CharField(
                choices=[
                    ("cash", "Tiền mặt"),
                    ("momo", "Ví MoMo"),
                    ("bank", "Chuyển khoản"),
                ],
                default="cash",
                max_length=20,
                verbose_name="Thanh toán qua",
            ),
        ),
        migrations.AddField(
            model_name="datsan",
            name="soLuongTuyen",
            field=models.IntegerField(
                blank=True,
                default=0,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="Số lượng cần tuyển",
            ),
        ),
        migrations.AddField(
            model_name="datsan",
            name="tuyenThanhVien",
            field=models.BooleanField(
                default=False, verbose_name="Bật tuyển thành viên giao lưu"
            ),
        ),
        migrations.AddField(
            model_name="nguoidung",
            name="is_phone_verified",
            field=models.BooleanField(default=False, verbose_name="Đã xác thực SĐT"),
        ),
        migrations.AddField(
            model_name="nguoidung",
            name="role",
            field=models.CharField(
                choices=[
                    ("customer", "Khách hàng"),
                    ("staff", "Nhân viên sân"),
                    ("manager", "Quản lý chi nhánh"),
                ],
                default="customer",
                max_length=20,
                verbose_name="Vai trò",
            ),
        ),
        migrations.AddField(
            model_name="sancaulong",
            name="giaCuoiTuan",
            field=models.DecimalField(
                decimal_places=0,
                default=70000,
                max_digits=10,
                verbose_name="Giá cuối tuần (T7, CN)",
            ),
        ),
        migrations.AddField(
            model_name="sancaulong",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Đang hoạt động"),
        ),
        migrations.AlterField(
            model_name="baidang",
            name="file_dinh_kem",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="diendan/files/",
                verbose_name="Tài liệu (PDF)",
            ),
        ),
        migrations.AlterField(
            model_name="binhluan",
            name="bai_dang",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="binh_luan_set",
                to="members.baidang",
            ),
        ),
        migrations.AlterField(
            model_name="binhluan",
            name="nguoi_binh_luan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="binhluan",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="members.binhluan",
            ),
        ),
        migrations.AlterField(
            model_name="datsan",
            name="ngayBatDau",
            field=models.DateField(verbose_name="Ngày chơi"),
        ),
        migrations.AlterField(
            model_name="hoithoaikhachhang",
            name="nguoi_dung",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="hotro",
            name="cau_hoi",
            field=models.TextField(verbose_name="Tin nhắn khách"),
        ),
        migrations.AlterField(
            model_name="hotro",
            name="da_xem",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="hotro",
            name="tra_loi",
            field=models.TextField(
                blank=True, null=True, verbose_name="Phản hồi Admin"
            ),
        ),
        migrations.AlterField(
            model_name="sancaulong",
            name="giaGioThuong",
            field=models.DecimalField(
                decimal_places=0,
                default=50000,
                max_digits=10,
                verbose_name="Giá giờ thường (Thứ 2-6)",
            ),
        ),
        migrations.AlterField(
            model_name="sancaulong",
            name="giaGioVang",
            field=models.DecimalField(
                decimal_places=0,
                default=80000,
                max_digits=10,
                verbose_name="Giá giờ vàng (17h-21h)",
            ),
        ),
        migrations.AlterField(
            model_name="sancaulong",
            name="gia_thang_3_buoi",
            field=models.DecimalField(
                decimal_places=0,
                default=600000,
                max_digits=12,
                verbose_name="Giá cố định (3 buổi/tuần)",
            ),
        ),
        migrations.AlterField(
            model_name="sancaulong",
            name="gia_thang_full",
            field=models.DecimalField(
                decimal_places=0,
                default=1200000,
                max_digits=12,
                verbose_name="Giá cố định (Full tuần)",
            ),
        ),
        migrations.CreateModel(
            name="ThongBao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tieu_de", models.CharField(max_length=255)),
                ("noi_dung", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "nguoi_nhan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thong_bao",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Thông báo",
                "verbose_name_plural": "Thông báo hệ thống",
                "ordering": ["-created_at"],
            },
        ),
    ]
