# Generated by Django 6.0 on 2026-01-05 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0007_alter_baidang_options_alter_binhluan_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nguoidung",
            name="chi_nhanh_quan_ly",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="members.chinhanh",
                verbose_name="Quản lý chi nhánh",
            ),
        ),
        migrations.AlterField(
            model_name="sancaulong",
            name="giaCuoiTuan",
            field=models.DecimalField(
                decimal_places=0,
                default=70000,
                max_digits=10,
                verbose_name="Giá cuối tuần",
            ),
        ),
        migrations.AlterField(
            model_name="sancaulong",
            name="giaGioThuong",
            field=models.DecimalField(
                decimal_places=0,
                default=50000,
                max_digits=10,
                verbose_name="Giá giờ thường",
            ),
        ),
        migrations.AlterField(
            model_name="sancaulong",
            name="giaGioVang",
            field=models.DecimalField(
                decimal_places=0,
                default=80000,
                max_digits=10,
                verbose_name="Giá giờ vàng (7h-17h)",
            ),
        ),
        migrations.CreateModel(
            name="TuyenThanhVien",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tieu_de", models.CharField(max_length=255, verbose_name="Tiêu đề")),
                (
                    "khu_vuc",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Khu vực"
                    ),
                ),
                (
                    "san_choi",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Sân chơi (nếu có)",
                    ),
                ),
                (
                    "trinh_do",
                    models.CharField(
                        choices=[
                            ("yeu", "Yếu / Mới chơi"),
                            ("tb", "Trung bình"),
                            ("kha", "Khá"),
                            ("gioi", "Giỏi / Chuyên nghiệp"),
                        ],
                        default="tb",
                        max_length=20,
                        verbose_name="Trình độ yêu cầu",
                    ),
                ),
                (
                    "thoi_gian",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Thời gian"
                    ),
                ),
                (
                    "chi_phi",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Chi phí"
                    ),
                ),
                (
                    "so_luong_can",
                    models.IntegerField(default=1, verbose_name="Số lượng cần tuyển"),
                ),
                (
                    "sdt_lien_he",
                    models.CharField(max_length=15, verbose_name="SĐT liên hệ"),
                ),
                (
                    "mo_ta",
                    models.TextField(blank=True, null=True, verbose_name="Mô tả thêm"),
                ),
                ("ngay_dang", models.DateTimeField(auto_now_add=True)),
                (
                    "da_du",
                    models.BooleanField(default=False, verbose_name="Đã đủ người"),
                ),
                (
                    "nguoi_dang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người đăng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tin tuyển thành viên",
                "verbose_name_plural": "Quản lý Tuyển quân (Rao vặt)",
                "ordering": ["-ngay_dang"],
            },
        ),
    ]
