# Generated by Django 6.0 on 2026-01-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0008_nguoidung_chi_nhanh_quan_ly_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sancaulong",
            options={
                "verbose_name": "Sân cầu lông",
                "verbose_name_plural": "Quản lý Sân",
            },
        ),
        migrations.RemoveField(
            model_name="sancaulong",
            name="giaCuoiTuan",
        ),
        migrations.RemoveField(
            model_name="sancaulong",
            name="giaGioThuong",
        ),
        migrations.RemoveField(
            model_name="sancaulong",
            name="giaGioVang",
        ),
        migrations.RemoveField(
            model_name="sancaulong",
            name="gia_thang_3_buoi",
        ),
        migrations.RemoveField(
            model_name="sancaulong",
            name="gia_thang_full",
        ),
        migrations.AddField(
            model_name="sancaulong",
            name="gia_co_dinh",
            field=models.DecimalField(
                decimal_places=0,
                default=60000,
                help_text="Giá ưu đãi dành cho khách đặt lịch cố định/tháng",
                max_digits=10,
                verbose_name="Giá CỐ ĐỊNH",
            ),
        ),
        migrations.AddField(
            model_name="sancaulong",
            name="gia_thuong",
            field=models.DecimalField(
                decimal_places=0,
                default=50000,
                help_text="Áp dụng cho khách vãng lai ngoài khung giờ vàng",
                max_digits=10,
                verbose_name="Giá giờ THƯỜNG",
            ),
        ),
        migrations.AddField(
            model_name="sancaulong",
            name="gia_vang",
            field=models.DecimalField(
                decimal_places=0,
                default=80000,
                help_text="Áp dụng cho khách vãng lai khung giờ 7h-17h",
                max_digits=10,
                verbose_name="Giá giờ VÀNG",
            ),
        ),
        migrations.AlterField(
            model_name="datsan",
            name="lich_tap",
            field=models.CharField(
                blank=True,
                choices=[
                    ("246", "Thứ 2 - 4 - 6"),
                    ("357", "Thứ 3 - 5 - 7"),
                    ("full", "Cả tuần (T2 - CN)"),
                    ("246cn", "Thứ 2 - 4 - 6 - CN"),
                    ("357cn", "Thứ 3 - 5- 7 - CN"),
                ],
                max_length=20,
                null=True,
                verbose_name="Lịch tập",
            ),
        ),
    ]
