# Generated by Django 6.0 on 2026-06-11 09:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_sancaulong_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datsan',
            name='soLuongTuyen',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Số lượng cần tuyển'),
        ),
    ]
