# Generated by Django 6.0 on 2026-06-16 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_transfer_content(apps, schema_editor):
    DatSan = apps.get_model('members', 'DatSan')
    for booking in DatSan.objects.select_related('san').all():
        if booking.noi_dung_chuyen_khoan or not booking.san_id:
            continue
        ngay = booking.ngayBatDau.strftime("%d/%m/%Y")
        gio = f"{booking.gioBatDau.strftime('%H:%M')}-{booking.gioKetThuc.strftime('%H:%M')}"
        ten = booking.tenNguoiDat or ""
        booking.noi_dung_chuyen_khoan = f"{ngay}-{gio}-{booking.san.tenSan}-{ten}".strip("-")
        booking.save(update_fields=['noi_dung_chuyen_khoan'])


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_alter_sancaulong_gia_thuong_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chinhanh',
            name='chu_tai_khoan',
            field=models.CharField(blank=True, max_length=150, verbose_name='Chủ tài khoản'),
        ),
        migrations.AddField(
            model_name='chinhanh',
            name='qr_thanh_toan',
            field=models.ImageField(blank=True, null=True, upload_to='payments/qr/', verbose_name='Mã QR thanh toán'),
        ),
        migrations.AddField(
            model_name='chinhanh',
            name='so_tai_khoan',
            field=models.CharField(blank=True, max_length=50, verbose_name='Số tài khoản'),
        ),
        migrations.AddField(
            model_name='chinhanh',
            name='ten_ngan_hang',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ngân hàng'),
        ),
        migrations.AddField(
            model_name='datsan',
            name='nguoi_duyet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='don_dat_san_da_duyet', to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt'),
        ),
        migrations.AddField(
            model_name='datsan',
            name='noi_dung_chuyen_khoan',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nội dung chuyển khoản'),
        ),
        migrations.AddField(
            model_name='hotro',
            name='nguon_tra_loi',
            field=models.CharField(choices=[('admin', 'Admin'), ('ai', 'AI')], default='admin', max_length=20, verbose_name='Nguồn phản hồi'),
        ),
        migrations.AddField(
            model_name='hotro',
            name='yeu_cau_admin',
            field=models.BooleanField(default=False, verbose_name='Khách yêu cầu admin'),
        ),
        migrations.AlterField(
            model_name='datsan',
            name='phuong_thuc_thanh_toan',
            field=models.CharField(choices=[('cash', 'Tiền mặt'), ('qr', 'Quét mã QR'), ('bank', 'Chuyển khoản'), ('momo', 'Ví MoMo')], default='cash', max_length=20, verbose_name='Thanh toán qua'),
        ),
        migrations.RunPython(backfill_transfer_content, migrations.RunPython.noop),
    ]
