# Generated by Django 6.0 on 2026-06-16 12:24

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_hoithoaikhachhang_admin_phu_trach_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datsan',
            name='khach_xac_nhan_chuyen_khoan',
            field=models.BooleanField(default=False, verbose_name='Khách đã bấm đã chuyển khoản'),
        ),
        migrations.AddField(
            model_name='datsan',
            name='ngay_gui_yeu_cau_thanh_toan',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày gửi yêu cầu thanh toán'),
        ),
        migrations.AddField(
            model_name='datsan',
            name='ngay_khach_xac_nhan_ck',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày khách xác nhận chuyển khoản'),
        ),
        migrations.AddField(
            model_name='datsan',
            name='so_tien_coc',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Số tiền cọc'),
        ),
        migrations.AddField(
            model_name='datsan',
            name='yeu_cau_thanh_toan',
            field=models.BooleanField(default=False, verbose_name='Đã gửi yêu cầu thanh toán'),
        ),
        migrations.AddField(
            model_name='nguoidung',
            name='failed_login_attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Số lần đăng nhập sai'),
        ),
        migrations.AddField(
            model_name='nguoidung',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Khóa đến'),
        ),
        migrations.AlterField(
            model_name='baidang',
            name='file_dinh_kem',
            field=models.FileField(blank=True, null=True, upload_to=core.models.forum_file_upload_to, verbose_name='Tài liệu (PDF)'),
        ),
        migrations.AlterField(
            model_name='baidang',
            name='hinh_anh',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.forum_image_upload_to, verbose_name='Hình ảnh minh họa'),
        ),
        migrations.AlterField(
            model_name='chinhanh',
            name='hinhAnh',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.branch_image_upload_to, verbose_name='Hình ảnh'),
        ),
        migrations.AlterField(
            model_name='chinhanh',
            name='qr_thanh_toan',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.branch_qr_upload_to, verbose_name='Mã QR thanh toán'),
        ),
        migrations.AlterField(
            model_name='datsan',
            name='phuong_thuc_thanh_toan',
            field=models.CharField(choices=[('cash', 'Tiền mặt'), ('qr', 'Quét mã QR'), ('bank', 'Chuyển khoản'), ('momo', 'Ví MoMo')], default='bank', max_length=20, verbose_name='Thanh toán qua'),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.avatar_upload_to, verbose_name='Ảnh đại diện'),
        ),
    ]
