# Generated by Django 6.0 on 2026-01-03 17:11

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChiNhanh",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tenChiNhanh",
                    models.CharField(max_length=255, verbose_name="Tên chi nhánh"),
                ),
                ("diaChi", models.CharField(max_length=255, verbose_name="Địa chỉ")),
                ("sdt", models.CharField(max_length=15, verbose_name="Hotline")),
                (
                    "tenQuanLy",
                    models.CharField(max_length=100, verbose_name="Tên quản lý"),
                ),
                (
                    "hinhAnh",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="chinhanh/",
                        verbose_name="Hình ảnh",
                    ),
                ),
                ("moTa", models.TextField(blank=True, null=True, verbose_name="Mô tả")),
                (
                    "linkMap",
                    models.URLField(
                        blank=True, null=True, verbose_name="Link Google Map"
                    ),
                ),
            ],
            options={
                "verbose_name": "Chi nhánh",
                "verbose_name_plural": "Quản lý Chi nhánh",
            },
        ),
        migrations.CreateModel(
            name="NguoiDung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "sodienthoai",
                    models.CharField(
                        max_length=15, unique=True, verbose_name="Số điện thoại"
                    ),
                ),
                ("ten", models.CharField(max_length=255, verbose_name="Họ và tên")),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="avatars/",
                        verbose_name="Ảnh đại diện",
                    ),
                ),
                (
                    "diem_thuong",
                    models.IntegerField(default=0, verbose_name="Điểm thưởng"),
                ),
                (
                    "dia_chi",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Địa chỉ"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Người dùng",
                "verbose_name_plural": "Quản lý Người dùng",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="BaiDang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tieu_de", models.CharField(max_length=255, verbose_name="Tiêu đề")),
                ("noi_dung", models.TextField(verbose_name="Nội dung chi tiết")),
                (
                    "hinh_anh",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="diendan/images/",
                        verbose_name="Hình ảnh minh họa",
                    ),
                ),
                (
                    "file_dinh_kem",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="diendan/files/",
                        verbose_name="File đính kèm (PDF)",
                    ),
                ),
                (
                    "ngay_dang",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày đăng"),
                ),
                (
                    "duyet_bai",
                    models.BooleanField(default=False, verbose_name="Đã duyệt"),
                ),
                ("luot_xem", models.IntegerField(default=0, verbose_name="Lượt xem")),
                (
                    "nguoi_dang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người đăng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bài viết diễn đàn",
                "verbose_name_plural": "Quản lý Diễn đàn",
                "ordering": ["-ngay_dang"],
            },
        ),
        migrations.CreateModel(
            name="HoiThoaiKhachHang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tieu_de",
                    models.CharField(
                        default="Hỗ trợ chung", max_length=255, verbose_name="Chủ đề"
                    ),
                ),
                ("ngay_tao", models.DateTimeField(auto_now_add=True)),
                ("ten", models.CharField(blank=True, max_length=255)),
                ("sodienthoai", models.CharField(blank=True, max_length=15)),
                (
                    "nguoi_dung",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Khách hàng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hội thoại hỗ trợ",
                "verbose_name_plural": "Danh sách Hội thoại",
            },
        ),
        migrations.CreateModel(
            name="HoTro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cau_hoi", models.TextField(verbose_name="Tin nhắn của khách")),
                (
                    "tra_loi",
                    models.TextField(
                        blank=True, null=True, verbose_name="Phản hồi của Admin"
                    ),
                ),
                ("ngay_gui", models.DateTimeField(auto_now_add=True)),
                ("ngay_tra_loi", models.DateTimeField(blank=True, null=True)),
                ("da_xem", models.BooleanField(default=False, verbose_name="Đã xử lý")),
                (
                    "hoi_thoai",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hotro_set",
                        to="members.hoithoaikhachhang",
                    ),
                ),
                (
                    "nguoi_dung",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tin nhắn chi tiết",
                "verbose_name_plural": "Chi tiết Tin nhắn",
            },
        ),
        migrations.CreateModel(
            name="SanCauLong",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenSan", models.CharField(max_length=100, verbose_name="Tên sân")),
                (
                    "giaGioThuong",
                    models.DecimalField(
                        decimal_places=0,
                        default=50000,
                        max_digits=10,
                        verbose_name="Giá giờ thường",
                    ),
                ),
                (
                    "giaGioVang",
                    models.DecimalField(
                        decimal_places=0,
                        default=80000,
                        max_digits=10,
                        verbose_name="Giá giờ vàng",
                    ),
                ),
                (
                    "giaCoDinh",
                    models.DecimalField(
                        decimal_places=0,
                        default=1000000,
                        max_digits=12,
                        verbose_name="Giá cố định tháng",
                    ),
                ),
                (
                    "moTa",
                    models.TextField(blank=True, null=True, verbose_name="Mô tả thêm"),
                ),
                (
                    "maChiNhanh",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ds_san",
                        to="members.chinhanh",
                        verbose_name="Thuộc chi nhánh",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sân cầu lông",
                "verbose_name_plural": "Quản lý Sân",
            },
        ),
        migrations.CreateModel(
            name="DatSan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ngayBatDau", models.DateField(verbose_name="Ngày chơi")),
                ("gioBatDau", models.TimeField(verbose_name="Giờ bắt đầu")),
                ("gioKetThuc", models.TimeField(verbose_name="Giờ kết thúc")),
                (
                    "tongGiaTien",
                    models.DecimalField(
                        decimal_places=0, max_digits=12, verbose_name="Tổng tiền"
                    ),
                ),
                (
                    "daThanhToan",
                    models.BooleanField(default=False, verbose_name="Đã thanh toán"),
                ),
                (
                    "loaiDatSan",
                    models.IntegerField(
                        choices=[
                            (0, "Vãng lai (Theo giờ)"),
                            (1, "Cố định (Theo tháng)"),
                        ],
                        default=0,
                        verbose_name="Loại hình đặt",
                    ),
                ),
                (
                    "trangThai",
                    models.CharField(
                        choices=[
                            ("pending", "Chờ xác nhận"),
                            ("confirmed", "Đã xác nhận"),
                            ("cancelled", "Đã hủy"),
                            ("completed", "Đã hoàn thành"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                ("ngay_tao", models.DateTimeField(auto_now_add=True)),
                (
                    "tenNguoiDat",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Tên người đặt"
                    ),
                ),
                (
                    "sdt",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="SĐT liên hệ"
                    ),
                ),
                (
                    "nguoi_dat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Khách hàng",
                    ),
                ),
                (
                    "san",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.sancaulong",
                        verbose_name="Sân đặt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Đơn đặt sân",
                "verbose_name_plural": "Quản lý Đặt sân",
                "ordering": ["-ngay_tao"],
            },
        ),
    ]
