# Generated by Django 6.0 on 2026-01-03 17:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sancaulong",
            name="giaCoDinh",
        ),
        migrations.AddField(
            model_name="datsan",
            name="lich_tap",
            field=models.CharField(
                blank=True,
                choices=[
                    ("246", "Thứ 2 - 4 - 6"),
                    ("357", "Thứ 3 - 5 - 7"),
                    ("full", "Cả tuần (T2 - CN)"),
                    ("246cn", "Thứ 2 - 4 - 6 - CN"),
                ],
                max_length=20,
                null=True,
                verbose_name="Lịch tập",
            ),
        ),
        migrations.AddField(
            model_name="datsan",
            name="nhom_dat_san",
            field=models.UUIDField(
                blank=True,
                default=uuid.uuid4,
                editable=False,
                null=True,
                verbose_name="Mã nhóm",
            ),
        ),
        migrations.AddField(
            model_name="sancaulong",
            name="gia_thang_3_buoi",
            field=models.DecimalField(
                decimal_places=0,
                default=600000,
                help_text="Áp dụng cho lịch 2-4-6 hoặc 3-5-7",
                max_digits=12,
                verbose_name="Giá tháng (3 buổi/tuần)",
            ),
        ),
        migrations.AddField(
            model_name="sancaulong",
            name="gia_thang_full",
            field=models.DecimalField(
                decimal_places=0,
                default=1200000,
                help_text="Áp dụng cho lịch cả tuần",
                max_digits=12,
                verbose_name="Giá tháng (Full tuần)",
            ),
        ),
    ]
