# Generated by Django 6.0 on 2026-01-04 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0004_alter_sancaulong_options_binhluan"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="binhluan",
            options={
                "ordering": ["ngay_tao"],
                "verbose_name": "Bình luận",
                "verbose_name_plural": "Quản lý Bình luận",
            },
        ),
        migrations.AlterField(
            model_name="binhluan",
            name="bai_dang",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="binh_luan_set",
                to="members.baidang",
                verbose_name="Bài viết",
            ),
        ),
        migrations.AlterField(
            model_name="binhluan",
            name="nguoi_binh_luan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Người bình luận",
            ),
        ),
        migrations.AlterField(
            model_name="binhluan",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="members.binhluan",
                verbose_name="Trả lời cho",
            ),
        ),
    ]
