# Generated by Django 6.0 on 2026-01-05 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0006_alter_baidang_options_alter_binhluan_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="baidang",
            options={
                "ordering": ["-ngay_dang"],
                "verbose_name": "Bài viết diễn đàn",
                "verbose_name_plural": "Quản lý Diễn đàn",
            },
        ),
        migrations.AlterModelOptions(
            name="binhluan",
            options={
                "ordering": ["ngay_tao"],
                "verbose_name": "Bình luận",
                "verbose_name_plural": "Quản lý Bình luận",
            },
        ),
        migrations.AlterModelOptions(
            name="hoithoaikhachhang",
            options={
                "verbose_name": "Hội thoại hỗ trợ",
                "verbose_name_plural": "Danh sách Hội thoại",
            },
        ),
        migrations.AlterModelOptions(
            name="hotro",
            options={
                "verbose_name": "Tin nhắn chi tiết",
                "verbose_name_plural": "Chi tiết Tin nhắn",
            },
        ),
        migrations.AlterModelOptions(
            name="sancaulong",
            options={
                "ordering": ["tenSan"],
                "verbose_name": "Sân cầu lông",
                "verbose_name_plural": "Quản lý Sân",
            },
        ),
        migrations.AddField(
            model_name="datsan",
            name="ghi_chu_tuyen",
            field=models.TextField(
                blank=True, null=True, verbose_name="Ghi chú tuyển (Phí/Kèo)"
            ),
        ),
        migrations.AddField(
            model_name="datsan",
            name="trinh_do_can",
            field=models.CharField(
                blank=True,
                choices=[
                    ("yeu", "Yếu / Mới chơi"),
                    ("tb", "Trung bình"),
                    ("kha", "Khá"),
                    ("gioi", "Giỏi / Chuyên nghiệp"),
                ],
                default="tb",
                max_length=20,
                null=True,
                verbose_name="Trình độ mong muốn",
            ),
        ),
        migrations.AlterField(
            model_name="binhluan",
            name="bai_dang",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="binh_luan_set",
                to="members.baidang",
                verbose_name="Bài viết",
            ),
        ),
        migrations.AlterField(
            model_name="binhluan",
            name="nguoi_binh_luan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Người bình luận",
            ),
        ),
        migrations.AlterField(
            model_name="binhluan",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="members.binhluan",
                verbose_name="Trả lời cho",
            ),
        ),
        migrations.AlterField(
            model_name="hoithoaikhachhang",
            name="nguoi_dung",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Khách hàng",
            ),
        ),
        migrations.AlterField(
            model_name="hotro",
            name="cau_hoi",
            field=models.TextField(verbose_name="Tin nhắn"),
        ),
    ]
