# Generated by Django 6.0 on 2026-06-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_alter_datsan_soluongtuyen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sancaulong',
            name='gia_thuong',
            field=models.DecimalField(decimal_places=0, default=50000, help_text='Áp dụng cho khách vãng lai từ 17h trở đi', max_digits=10, verbose_name='Giá giờ THƯỜNG'),
        ),
        migrations.AlterField(
            model_name='sancaulong',
            name='gia_vang',
            field=models.DecimalField(decimal_places=0, default=80000, help_text='Áp dụng cho khách vãng lai trước 17h', max_digits=10, verbose_name='Giá giờ VÀNG'),
        ),
    ]
