# Generated by Django 6.0 on 2026-06-16 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_support_branch(apps, schema_editor):
    HoiThoaiKhachHang = apps.get_model('members', 'HoiThoaiKhachHang')
    DatSan = apps.get_model('members', 'DatSan')
    NguoiDung = apps.get_model('members', 'NguoiDung')

    for conversation in HoiThoaiKhachHang.objects.filter(chi_nhanh__isnull=True):
        booking = (
            DatSan.objects.filter(nguoi_dat=conversation.nguoi_dung)
            .select_related('san__maChiNhanh')
            .order_by('-ngay_tao')
            .first()
        )
        if not booking:
            continue
        branch = booking.san.maChiNhanh
        admin = (
            NguoiDung.objects.filter(chi_nhanh_quan_ly=branch)
            .filter(models.Q(role__in=['staff', 'manager']) | models.Q(is_staff=True) | models.Q(is_superuser=True))
            .order_by('-is_staff', 'id')
            .first()
        )
        conversation.chi_nhanh = branch
        conversation.admin_phu_trach = admin
        conversation.save(update_fields=['chi_nhanh', 'admin_phu_trach'])


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_chinhanh_chu_tai_khoan_chinhanh_qr_thanh_toan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoithoaikhachhang',
            name='admin_phu_trach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hoi_thoai_phu_trach', to=settings.AUTH_USER_MODEL, verbose_name='Admin phụ trách'),
        ),
        migrations.AddField(
            model_name='hoithoaikhachhang',
            name='can_admin',
            field=models.BooleanField(default=False, verbose_name='Cần admin chi nhánh xử lý'),
        ),
        migrations.AddField(
            model_name='hoithoaikhachhang',
            name='chi_nhanh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hoi_thoai_ho_tro', to='members.chinhanh', verbose_name='Chi nhánh hỗ trợ'),
        ),
        migrations.AddField(
            model_name='hoithoaikhachhang',
            name='da_dong',
            field=models.BooleanField(default=False, verbose_name='Đã đóng hội thoại'),
        ),
        migrations.AddField(
            model_name='hoithoaikhachhang',
            name='last_admin_request_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Lần yêu cầu admin gần nhất'),
        ),
        migrations.AddField(
            model_name='hotro',
            name='admin_tra_loi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phan_hoi_ho_tro', to=settings.AUTH_USER_MODEL, verbose_name='Admin trả lời'),
        ),
        migrations.RunPython(backfill_support_branch, migrations.RunPython.noop),
    ]
