# Generated by Django 6.0 on 2026-06-18 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0017_update_court_price_defaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="datsan",
            name="ngay_khach_mo_thanh_toan",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Ngày khách mở yêu cầu thanh toán"
            ),
        ),
    ]
