# Generated by Django 6.0 on 2026-06-18 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0018_datsan_ngay_khach_mo_thanh_toan"),
    ]

    operations = [
        migrations.AddField(
            model_name="thongbao",
            name="duong_dan",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Đường dẫn xử lý"
            ),
        ),
        migrations.AddField(
            model_name="thongbao",
            name="loai",
            field=models.CharField(
                choices=[
                    ("booking", "Đặt sân"),
                    ("post", "Bài viết"),
                    ("support", "Hỗ trợ"),
                    ("payment", "Thanh toán"),
                    ("system", "Hệ thống"),
                ],
                default="system",
                max_length=20,
                verbose_name="Loại thông báo",
            ),
        ),
    ]
